using Oscar
Qx, s = polynomial_ring(QQ, :s);

# For the rest of the computations, we only need the algebraic number sqrt(-3), hence we can pass to a smaller number field
M, q3 = number_field(s^2 + 3, "q3");

# In order to compute the blowups along the previously computed varieties belonging to delta_11 and delta_21, we first define a polynomial ring that represents the coordinate ring of the quotient variety
# We add the variable t to compute the Rees algebra of the ideal of the variety we want to blow up
Bt, y, t = polynomial_ring(M, :y => (1:12), :t => (1:1));

# The coordinate ring of the quotient variety corresponds to the quotient of Bt by the relation ideal
relations_ideal = ideal(Bt, [
    2*y[2]*y[4] - 2*y[3]^2 + 9*y[1]^2*y[6],
    y[2]*y[6] - y[3]*y[5] + 3*y[1]*y[9],
    y[4]*y[6] - y[3]*y[7] - 3*y[1]*y[11],
    y[2]*y[7] - y[3]*y[6] + 3*y[1]*y[10] + 2*y[1]^4*y[3],
    y[4]*y[5] - y[3]*y[6] - 3*y[1]*y[10] + 2*y[1]^4*y[3],
    2*y[5]*y[7] - 2*y[6]^2 - 6*y[1]^2*y[3]^2 - y[1]^4*y[6],
    6*y[2]*y[9] - 6*y[3]*y[8] + 9*y[1]*y[5]^2 - y[1]^3*y[2]^2,
    6*y[4]*y[11] - 6*y[3]*y[12] - 9*y[1]*y[7]^2 + y[1]^3*y[4]^2,
    6*y[2]*y[10] - 6*y[3]*y[9] + 9*y[1]*y[5]*y[6] - 4*y[1]^3*y[2]*y[3],
    6*y[4]*y[10] - 6*y[3]*y[11] - 9*y[1]*y[7]*y[6] + 4*y[1]^3*y[4]*y[3],
    6*y[2]*y[11] - 6*y[3]*y[10] + 9*y[1]*y[6]^2 - 4*y[1]^3*y[3]^2,
    6*y[4]*y[9] - 6*y[3]*y[10] - 9*y[1]*y[6]^2 + 4*y[1]^3*y[3]^2,
    6*y[2]*y[12] - 6*y[3]*y[11] + 9*y[1]*y[6]*y[7] - 28*y[1]^3*y[3]*y[4] - 36*y[1]^5*y[7],
    6*y[4]*y[8] - 6*y[3]*y[9] - 9*y[1]*y[6]*y[5] + 28*y[1]^3*y[3]*y[2] + 36*y[1]^5*y[5],
    3*y[5]*y[9] - 3*y[6]*y[8] + 3*y[1]*y[2]^2*y[3] + 4*y[1]^3*y[2]*y[5],
    3*y[7]*y[11] - 3*y[6]*y[12] - 3*y[1]*y[4]^2*y[3] - 4*y[1]^3*y[4]*y[7],
    6*y[5]*y[10] - 6*y[6]*y[9] + 6*y[1]*y[2]*y[3]^2 + 4*y[1]^3*y[3]*y[5] + y[1]^3*y[2]*y[6],
    6*y[7]*y[10] - 6*y[6]*y[11] - 6*y[1]*y[4]*y[3]^2 - 4*y[1]^3*y[3]*y[7] - y[1]^3*y[4]*y[6],
    6*y[5]*y[11] - 6*y[6]*y[10] + 6*y[1]*y[3]^3 + 5*y[1]^3*y[3]*y[6],
    6*y[7]*y[9] - 6*y[6]*y[10] - 6*y[1]*y[3]^3 - 5*y[1]^3*y[3]*y[6],
    6*y[5]*y[12] - 6*y[6]*y[11] + 6*y[1]*y[3]^2*y[4] + 35*y[1]^3*y[4]*y[6] - 84*y[1]^4*y[11] + 4*y[1]^7*y[4],
    6*y[7]*y[8] - 6*y[6]*y[9] - 6*y[1]*y[3]^2*y[2] - 35*y[1]^3*y[2]*y[6] - 84*y[1]^4*y[9] - 4*y[1]^7*y[2],
    36*y[8]*y[10] - 36*y[9]^2 + 54*y[1]^2*y[2]*y[3]*y[5] - 18*y[1]^3*y[8]*y[3] + 63*y[1]^4*y[5]^2 + y[1]^6*y[2]^2,
    36*y[12]*y[10] - 36*y[11]^2 + 54*y[1]^2*y[4]*y[3]*y[7] + 18*y[1]^3*y[12]*y[3] + 63*y[1]^4*y[7]^2 + y[1]^6*y[4]^2,
    9*y[8]*y[11] - 9*y[9]*y[10] + 27*y[1]^2*y[2]*y[3]*y[6] + 36*y[1]^3*y[9]*y[3] + 18*y[1]^4*y[5]*y[6] + 2*y[1]^6*y[2]*y[3],
    9*y[12]*y[9] - 9*y[11]*y[10] + 27*y[1]^2*y[4]*y[3]*y[6] - 36*y[1]^3*y[11]*y[3] + 18*y[1]^4*y[7]*y[6] + 2*y[1]^6*y[4]*y[3],
    2*y[8]*y[12] - 2*y[9]*y[11] + 9*y[1]^2*y[2]*y[4]*y[6] + 48*y[1]^4*y[6]^2 + 32*y[1]^6*y[2]*y[4] + 132*y[1]^8*y[6] - 8*y[1]^12,
    18*y[9]*y[11] - 18*y[10]^2 + 27*y[1]^2*y[2]*y[4]*y[6] + 126*y[1]^4*y[6]^2 + 8*y[1]^6*y[3]^2,
    6*y[8]*y[9] - 3*y[5]^3 + 2*y[2]^3*y[3] + 3*y[1]^2*y[2]^2*y[5],
    6*y[12]*y[11] - 3*y[7]^3 + 2*y[4]^3*y[3] + 3*y[1]^2*y[4]^2*y[7],
    6*y[9]^2 - 3*y[5]^2*y[6] + 2*y[2]^3*y[4] + 12*y[1]^2*y[2]*y[3]*y[5] - 28*y[1]^3*y[2]*y[9],
    6*y[11]^2 - 3*y[7]^2*y[6] + 2*y[4]^3*y[2] + 12*y[1]^2*y[4]*y[3]*y[7] + 28*y[1]^3*y[4]*y[11],
    6*y[9]*y[10] - 3*y[5]*y[6]^2 + 2*y[2]*y[3]^3 + 3*y[1]^2*y[2]*y[3]*y[6] + 4*y[1]^3*y[3]*y[9],
    6*y[11]*y[10] - 3*y[7]*y[6]^2 + 2*y[4]*y[3]^3 + 3*y[1]^2*y[4]*y[3]*y[6] - 4*y[1]^3*y[3]*y[11],
    18*y[10]^2 - 9*y[5]*y[6]*y[7] + 6*y[3]^4 + 9*y[1]^2*y[3]^2*y[6] - 8*y[1]^6*y[3]^2
]);

# Define the generators of the ideals corresponding to delta_11 and delta_21 along which we want to blow up
w_11_1 = q3*y[1]*y[2] + 3*y[5];
w_11_2 = 6*y[1]^4 + 4*q3*y[1]*y[3] + 3*y[6];
w_11_3 = -q3*y[2]^2 + 3*y[8];
w_11_4 = -2*q3*y[1]^2*y[5] - q3*y[2]*y[3] + 3*y[9];
w_11_5 = -4*y[1]^3*y[3] - (1//q3)*y[2]*y[4] + (4//q3)*y[3]^2 + 3*y[10];
# Define the vector used to construct the underlying map of the blowup along the divisor W_delta_11
blowup_vector_11 = [y[1], y[2], y[3], y[4], y[5], y[6], y[7], y[8], y[9], y[10], y[11], y[12], t[1]*w_11_1, t[1]*w_11_2, t[1]*w_11_3, t[1]*w_11_4, t[1]*w_11_5];

w_21_1 = -q3*y[1]*y[2] + 3*y[5];
w_21_2 = 6*y[1]^4 - 4*q3*y[1]*y[3] + 3*y[6];
w_21_3 = q3*y[2]^2 + 3*y[8];
w_21_4 = 2*q3*y[1]^2*y[5] + q3*y[2]*y[3] + 3*y[9];
w_21_5 = -4*y[1]^3*y[3] + q3*y[2]*y[4] - (4//q3)*y[3]^2 + 3*y[10];
# Define the vector used to construct the underlying map of the blowup along the divisor W_delta_21
blowup_vector_21 = [y[1], y[2], y[3], y[4], y[5], y[6], y[7], y[8], y[9], y[10], y[11], y[12], t[1]*w_21_1, t[1]*w_21_2, t[1]*w_21_3, t[1]*w_21_4, t[1]*w_21_5];

# Define the ring C=B[b_1,...,b_5] used to compute the rees algebra of the blowups, which both can be embedded into this relative projective space as the ideals along which we blow up are generated by 5 elements
C, y, b = polynomial_ring(M, :y => (1:12), :b => (1:5));

# Compute the blowup along W_delta_11
blowup_map_11 = hom(C, Bt, blowup_vector_11);
kernel_blowup_map_11 = preimage(blowup_map_11, relations);
basis_blowup_11 = standard_basis(kernel_blowup_map_11, ordering=negdegrevlex(C));  # Get a smaller generating set of the blowup ideal
basis_blowup_ideal_11 = ideal(C, collect(basis_blowup_11));

# Compute the blowup along W_delta_21
blowup_map_21 = hom(C, Bt, blowup_vector_21);
kernel_blowup_map_21 = preimage(blowup_map_21, relations);
basis_blowup_21 = standard_basis(kernel_blowup_map_21, ordering=negdegrevlex(C));  # Get a smaller generating set of the blowup ideal
basis_blowup_ideal_21 = ideal(C, collect(basis_blowup_21));
