using Oscar
Q_t, t = polynomial_ring(QQ, :t);
K, zeta = number_field(t^8 - t^4 + 1, "zeta");
i = zeta^6;      # imaginary unit
sigma = zeta^8;  # primitive third root of unity
q2 = zeta^3 + zeta^(-3); # sqrt(2)
q3 = zeta^8 - zeta^(-8); # sqrt(3)

# Matrix representations of generators of the group G_5 as subgroup of GL_2(CC)
a = matrix(K, 2, 2, [i 0; 0 -i]);
b = matrix(K, 2, 2, [0 1; -1 0]);
c = matrix(K, 2, 2, [zeta//q2 (-zeta)//q2; (i*zeta)//q2 (i*zeta)//q2]);
d = matrix(K, 2, 2, [sigma, 0, 0, sigma]);

c_conj = a*c*d^2

G_5 = matrix_group([a, b, c, c_conj]);
describe(G_5);

conj = conjugacy_classes(G_5);

# Compute the corresponding symplectic reflection group
a_symp = block_diagonal_matrix([a, transpose(inv(a))]);
b_symp = block_diagonal_matrix([b, transpose(inv(b))]);
c_symp = block_diagonal_matrix([c, transpose(inv(c))]);
d_symp = block_diagonal_matrix([d, transpose(inv(d))]);
c_conj_symp = block_diagonal_matrix([c_conj, transpose(inv(c_conj))]);
G_5_symp = matrix_group([a_symp, b_symp, c_symp, c_conj_symp]);

# Compute the invariants of the symplectic reflection group
IR = invariant_ring(G_5_symp);
poly_invar = polynomial_ring(IR);
u = gens(poly_invar);
invars = fundamental_invariants(IR);
invars_ideal_1 = ideal(poly_invar, invars);

# In order to compare with the invariants given by Berry, we consider the corresponding polynomials in the polynomial ring R in 4 variables
R, x = polynomial_ring(K, :x => (1:4));

# Invariants of G_5_symp by the above computation
invar_1 = x[1]*x[3] + x[2]*x[4];
invar_2 = x[1]^5*x[2] - x[1]*x[2]^5;
invar_3 = x[1]*x[2]^2*x[3]^3 - x[2]^3*x[3]^2*x[4] - x[1]^3*x[3]*x[4]^2 + x[1]^2*x[2]*x[4]^3;
invar_4 = x[3]^5*x[4] - x[3]*x[4]^5;
invar_5 = x[1]^4*x[2]^3*x[3] + 1//7*x[2]^7*x[3] - 1//7*x[1]^7*x[4] - x[1]^3*x[2]^4*x[4];
invar_6 = x[2]^4*x[3]^4 - 4*x[1]^3*x[2]*x[3]^3*x[4] + 6*x[1]^2*x[2]^2*x[3]^2*x[4]^2 - 4*x[1]*x[2]^3*x[3]*x[4]^3 + x[1]^4*x[4]^4;
invar_7 = x[2]*x[3]^7 - 7*x[1]*x[3]^4*x[4]^3 + 7*x[2]*x[3]^3*x[4]^4 - x[1]*x[4]^7;
invar_8 = x[3]^12 - 33*x[3]^8*x[4]^4 - 33*x[3]^4*x[4]^8 + x[4]^12;
invar_9 = x[2]^3*x[3]^9 + 3//5*x[1]^3*x[3]^8*x[4] - 36//5*x[1]^2*x[2]*x[3]^7*x[4]^2 + 84//5*x[1]*x[2]^2*x[3]^6*x[4]^3 - 42//5*x[2]^3*x[3]^5*x[4]^4 + 42//5*x[1]^3*x[3]^4*x[4]^5 - 84//5*x[1]^2*x[2]*x[3]^3*x[4]^6 + 36//5*x[1]*x[2]^2*x[3]^2*x[4]^7 -3//5*x[2]^3*x[3]*x[4]^8 - x[1]^3*x[4]^9;
invar_10 = x[1]^4*x[2]^2*x[3]^6 - 1//17*x[2]^6*x[3]^6 + 24//17*x[1]^3*x[2]^3*x[3]^5*x[4] - 15//17*x[1]^6*x[3]^4*x[4]^2 + 15//17*x[1]^2*x[2]^4*x[3]^4*x[4]^2 - 40//17*x[1]^5*x[2]*x[3]^3*x[4]^3 - 40//17*x[1]*x[2]^5*x[3]^3*x[4]^3 + 15//17*x[1]^4*x[2]^2*x[3]^2*x[4]^4 - 15//17*x[2]^6*x[3]^2*x[4]^4 + 24//17*x[1]^3*x[2]^3*x[3]*x[4]^5 - 1//17*x[1]^6*x[4]^6 + x[1]^2*x[2]^4*x[4]^6;
invar_11 = x[1]^8*x[2]*x[3]^3 - 14//23*x[1]^4*x[2]^5*x[3]^3 - 1//23*x[2]^9*x[3]^3 + 60//23*x[1]^7*x[2]^2*x[3]^2*x[4] - 84//23*x[1]^3*x[2]^6*x[3]^2*x[4] + 84//23*x[1]^6*x[2]^3*x[3]*x[4]^2 - 60//23*x[1]^2*x[2]^7*x[3]*x[4]^2 + 1//23*x[1]^9*x[4]^3 + 14//23*x[1]^5*x[2]^4*x[4]^3 - x[1]*x[2]^8*x[4]^3;
invar_12 = x[1]^12 - 33*x[1]^8*x[2]^4 - 33*x[1]^4*x[2]^8 + x[2]^12;
invars_ideal_1 = ideal(R, [invar_1, invar_2, invar_3, invar_4, invar_5, invar_6, invar_7, invar_8, invar_9, invar_10, invar_11, invar_12]);

# Eigenvectors of c and c_conj for the eigenvalue 1 according to Berry
F11 = x[1]*x[3] + x[2]*x[4];
F40 = x[1]^4 + x[2]^4 - 2*q3*x[1]^2*x[2]^2;
F31 = x[1]^3*x[4] - q3*x[1]^2*x[2]*x[3] + q3*x[1]*x[2]^2*x[4] - x[2]^3*x[3];
G22 = x[1]^2*x[3]^2 + q3*x[2]^2*x[3]^2 + q3*x[1]^2*x[4]^2 + x[2]^2*x[4]^2 - 4*x[1]*x[2]*x[3]*x[4];
F13 = x[1]*x[4]^3 + q3*x[2]*x[3]*x[4]^2 - q3*x[1]*x[3]^2*x[4] - x[2]*x[3]^3;
F04 = x[3]^4 + x[4]^4 + 2*q3*x[3]^2*x[4]^2;
F60 = x[1]^5*x[2] - x[1]*x[2]^5;
G51 = x[1]^5*x[3] - 5*x[1]^4*x[2]*x[4] - 5*x[1]*x[2]^4*x[3] + x[2]^5*x[4];
G42 = x[1]^4*x[3]*x[4] - 2*x[1]^3*x[2]*x[4]^2 + 2*x[1]*x[2]^3*x[3]^2 - x[2]^4*x[3]*x[4];
F33 = x[1]^3*x[3]*x[4]^2 - x[1]^2*x[2]*x[4]^3 - x[1]*x[2]^2*x[3]^3 + x[2]^3*x[3]^2*x[4];
G24 = 2*x[1]^2*x[3]*x[4]^3 + x[1]*x[2]*x[3]^4 - x[1]*x[2]*x[4]^4 - 2*x[2]^2*x[3]^3*x[4];
G15 = x[1]*x[3]^5 - 5*x[1]*x[3]*x[4]^4 - 5*x[2]*x[3]^4*x[4] + x[2]*x[4]^5;
F06 = x[3]^5*x[4] - x[3]*x[4]^5;

f_conj = hom(K, K, -zeta^7+zeta^3);
function conj_poly(poly)
    return map_coefficients(f_conj, poly)
end

F40_conj = conj_poly(F40);
F31_conj = conj_poly(F31);
G22_conj = conj_poly(G22);
F13_conj = conj_poly(F13);
F04_conj = conj_poly(F04);

gen_ideal = ideal(R, [F11, F40, F31, G22, F13, F04, F60, G51, G42, F33, G24, G15, F06, F40_conj, F31_conj, G22_conj, F13_conj, F04_conj]);

# Invariants as given by Berry
B1 = -F40*F31 - F40_conj*F31_conj;
B0 = F31*F13 + F31_conj*F13_conj;
Bneg1 = -F13*F04 - F13_conj*F04_conj;
C2 = F40^3 + F40_conj^3;
C1 = -F31^3 - F31_conj^3;
C0 = F40*F13^2 + F40_conj*F13_conj^2 + 4*F11^3*F33;
Cneg1 = -F13^3 - F13_conj^3;
Cneg2 = F04^3 + F04_conj^3;
h = F11;
A1 = 6*F60;
A0 = 3*F33;
Aneg1 = 6*F06;

invars_ideal_2 = ideal(R, [h, A1, A0, Aneg1, B1, B0, Bneg1, C2, C1, C0, Cneg1, Cneg2]);
print("The ideals generated by the invariants are equal: "; invars_ideal_1 == invars_ideal_2)  # confirm that both ideals are equal

# Now express the invariants invars_ideal_1 in terms of the invariants and eigenvectors given by Berry
I_9 = ideal(R, [Aneg1, Cneg1]);
print(ideal_membership(invar_9, I_9));
coeffs_9 = coordinates(invar_9, I_9);
print(1//10*F11^3*Aneg1+1//2*Cneg1 == invar_9);

I_10 = ideal(R, [A0, C0]);
print(ideal_membership(invar_10, I_10));
coeffs_10 = coordinates(invar_10, I_10);
print(-16//51*F11^3*A0-1//34*C0 == invar_10);

I_11 = ideal(R, [A1, C1]);
print(ideal_membership(invar_11, I_11));
coeffs_11 = coordinates(invar_11, I_11);
print(1//6*F11^3*A1-1//46*C1 == invar_11);

# The rest of the invariants can be directly expressed as scalar multiples, thus we can work with the invariants given by Berry

# Define polynomial ring in 12 variables to express the relations between the invariants
S, (y_h, y_A1, y_A0, y_Aneg1, y_B1, y_B0, y_Bneg1, y_C2, y_C1, y_C0, y_Cneg1, y_Cneg2) = polynomial_ring(K, [:y_h, :y_A1, :y_A0, :y_Aneg1, :y_B1, :y_B0, :y_Bneg1, :y_C2, :y_C1, :y_C0, :y_Cneg1, :y_Cneg2]);
# Define homomorphism from S to R mapping y_i to the invariants given by Berry
pi_1 = hom(S, R, [h, A1, A0, Aneg1, B1, B0, Bneg1, C2, C1, C0, Cneg1, Cneg2]);
#=# Compute kernel of f to obtain the relations
relations_ideal = kernel(f);
basis_relations = standard_basis(relations_ideal, ordering=negdegrevlex(S));

g = hom(S, R, [invar_1, invar_2, invar_3, invar_4, invar_5, invar_6, invar_7, invar_8, invar_9, invar_10, invar_11, invar_12]);
relations_ideal_1 = kernel(g);
print(relations_ideal == relations_ideal_1)  # confirm that both ideals are equal=#

# The above approach is not effienciently computable, therefore we use the approach of Appendix B in Berry's paper
A, (X, Y) = polynomial_ring(K, [:X, :Y]);
rho = hom(R, A, [X, Y, Y, -X]);

B, (z_A, z_B, z_C) = polynomial_ring(K, [:z_A, :z_B, :z_C]);
rho_bar = hom(S, B, [0, z_A, z_A, z_A, z_B, z_B, z_B, z_C, z_C, z_C, z_C, z_C]);
kernel_rho_bar = kernel(rho_bar);

# We want to compute the bihomogeneous kernel of rho_bar with respect to the grading given by W_S
W_S = [1 6 3 0 7 4 1 12 9 6 3 0; 1 0 3 6 1 4 7 0 3 6 9 12];

# As the map rho_bar does not respect the grading, we introduce auxiliary variables t1 and t2 that ensure that the new map rho_bar_hom respects the grading
Aux, (za, zb, zc, t1, t2) = polynomial_ring(K, ["zA", "zB", "zC", "t1", "t2"]);
base_images = [Aux(0), za, za, za, zb, zb, zb, zc, zc, zc, zc, zc];
rho_bar_hom_images = [base_images[i] * t1^W_S[1,i] * t2^W_S[2,i] for i in 1:12];
rho_bar_hom = hom(S, Aux, rho_bar_hom_images);
bihom_kernel_rho_bar = kernel(rho_bar_hom);

nu_A = rho(A1);
nu_B = rho(B1);
nu_C = rho(C2);
pi_2 = hom(B, A, [nu_A, nu_B, nu_C]);
pi_2_relations = kernel(pi_2);  # Is a principal ideal generarated by a single polyonomial

# In order to compute the bihomogeneous preimage of the relations of pi_2, we use the same auxiliary variables as above to ensure that the gradings are respected
pi_2_rel_aux_gen = 2*za^4 - 3*zb^3 + 6*zc^2;  # the unique generator of pi_2 relations transferred to the auxiliary ring
pi_2_rel_aux = ideal(Aux, pi_2_rel_aux_gen);

bihom_rho_bar_preimage = preimage(rho_bar_hom, pi_2_rel_aux);
#basis_bihom_rho_bar_preimage = standard_basis(bihom_rho_bar_preimage, ordering=negdegrevlex(Aux));

# Check if the ideal describing the kernel of rho_bar mathches the description that can be read off from the relations given by Berry
test_2 = ideal(S, [
2*y_A1*y_Aneg1 - 2*y_A0^2,
y_A1*y_B0 - y_A0*y_B1,
y_Aneg1*y_B0 - y_A0*y_Bneg1,
y_A1*y_Bneg1 - y_A0*y_B0,
y_Aneg1*y_B1 - y_A0*y_B0,
2*y_B1*y_Bneg1 - 2*y_B0^2,
6*y_A1*y_C1 - 6*y_A0*y_C2,
6*y_Aneg1*y_Cneg1 - 6*y_A0*y_Cneg2,
6*y_A1*y_C0 - 6*y_A0*y_C1,
6*y_Aneg1*y_C0 - 6*y_A0*y_Cneg1,
6*y_A1*y_Cneg1 - 6*y_A0*y_C0,
6*y_Aneg1*y_C1 - 6*y_A0*y_C0,
6*y_A1*y_Cneg2 - 6*y_A0*y_Cneg1,
6*y_Aneg1*y_C2 - 6*y_A0*y_C1,
3*y_B1*y_C1 - 3*y_B0*y_C2,
3*y_Bneg1*y_Cneg1 - 3*y_B0*y_Cneg2,
6*y_B1*y_C0 - 6*y_B0*y_C1,
6*y_Bneg1*y_C0 - 6*y_B0*y_Cneg1,
6*y_B1*y_Cneg1 - 6*y_B0*y_C0,
6*y_Bneg1*y_C1 - 6*y_B0*y_C0,
6*y_B1*y_Cneg2 - 6*y_B0*y_Cneg1,
6*y_Bneg1*y_C2 - 6*y_B0*y_C1,
36*y_C2*y_C0 - 36*y_C1^2,
36*y_Cneg2*y_C0 - 36*y_Cneg1^2,
9*y_C2*y_Cneg1 - 9*y_C1*y_C0,
9*y_Cneg2*y_C1 - 9*y_Cneg1*y_C0,
2*y_C2*y_Cneg2 - 2*y_C1*y_Cneg1,
18*y_C1*y_Cneg1 - 18*y_C0^2]);
test_3 = ideal(S, gens(bihom_rho_bar_preimage)[2:29]);
print("The kernel of rho_bar is generated by the first 28 relations given by Berry: ", test_2 == test_3);  # Returns true and thus confirms that the kernel of rho_bar is generated by the first 28 relations given by Berry

# Test whether the preimages of the relations given by Berry (the ideal I in the appendix of his paper) are contained in the previously computed bihomogeneous preimage of ker(pi_2) under rho_bar 
test_4 = ideal(S, [
    2*y_A1*y_Aneg1 - 2*y_A0^2,
    y_A1*y_B0 - y_A0*y_B1 ,
    y_Aneg1*y_B0 - y_A0*y_Bneg1,
    y_A1*y_Bneg1 - y_A0*y_B0,
    y_Aneg1*y_B1 - y_A0*y_B0,
    2*y_B1*y_Bneg1 - 2*y_B0^2,
    6*y_A1*y_C1 - 6*y_A0*y_C2,
    6*y_Aneg1*y_Cneg1 - 6*y_A0*y_Cneg2,
    6*y_A1*y_C0 - 6*y_A0*y_C1,
    6*y_Aneg1*y_C0 - 6*y_A0*y_Cneg1,
    6*y_A1*y_Cneg1 - 6*y_A0*y_C0,
    6*y_Aneg1*y_C1 - 6*y_A0*y_C0,
    6*y_A1*y_Cneg2 - 6*y_A0*y_Cneg1,
    6*y_Aneg1*y_C2 - 6*y_A0*y_C1,
    3*y_B1*y_C1 - 3*y_B0*y_C2,
    3*y_Bneg1*y_Cneg1 - 3*y_B0*y_Cneg2,
    6*y_B1*y_C0 - 6*y_B0*y_C1,
    6*y_Bneg1*y_C0 - 6*y_B0*y_Cneg1,
    6*y_B1*y_Cneg1 - 6*y_B0*y_C0,
    6*y_Bneg1*y_C1 - 6*y_B0*y_C0,
    6*y_B1*y_Cneg2 - 6*y_B0*y_Cneg1,
    6*y_Bneg1*y_C2 - 6*y_B0*y_C1,
    36*y_C2*y_C0 - 36*y_C1^2,
    36*y_Cneg2*y_C0 - 36*y_Cneg1^2,
    9*y_C2*y_Cneg1 - 9*y_C1*y_C0,
    9*y_Cneg2*y_C1 - 9*y_Cneg1*y_C0,
    2*y_C2*y_Cneg2 - 2*y_C1*y_Cneg1,
    18*y_C1*y_Cneg1 - 18*y_C0^2,
    6*y_C2*y_C1 - 3*y_B1^3 + 2*y_A1^3*y_A0,
    6*y_Cneg2*y_Cneg1 - 3*y_Bneg1^3 + 2*y_Aneg1^3*y_A0,
    6*y_C1^2 - 3*y_B1^2*y_B0 + 2*y_A1^3*y_Aneg1,
    6*y_Cneg1^2 - 3*y_Bneg1^2*y_B0 + 2*y_Aneg1^3*y_A1,
    6*y_C1*y_C0 - 3*y_B1*y_B0^2 + 2*y_A1*y_A0^3,
    6*y_Cneg1*y_C0 - 3*y_Bneg1*y_B0^2 + 2*y_Aneg1*y_A0^3,
    18*y_C0^2 - 9*y_B1*y_B0*y_Bneg1 + 6*y_A0^4
]);

print("The relations ideal is contained in the bihomogeneous part of the preimage: ", is_subset(test_4, bihom_rho_bar_preimage));

# The relations as they are given by Berry in appendix A
relation_list = [
    2*A1*Aneg1 - 2*A0^2 + 9*h^2*B0,
    A1*B0 - A0*B1 + 3*h*C1,
    Aneg1*B0 - A0*Bneg1 - 3*h*Cneg1,
    A1*Bneg1 - A0*B0 + 3*h*C0 + 2*h^4*A0,
    Aneg1*B1 - A0*B0 - 3*h*C0 + 2*h^4*A0,
    2*B1*Bneg1 - 2*B0^2 - 6*h^2*A0^2 - h^4*B0,
    6*A1*C1 - 6*A0*C2 + 9*h*B1^2 - h^3*A1^2,
    6*Aneg1*Cneg1 - 6*A0*Cneg2 - 9*h*Bneg1^2 + h^3*Aneg1^2,
    6*A1*C0 - 6*A0*C1 + 9*h*B1*B0 - 4*h^3*A1*A0,
    6*Aneg1*C0 - 6*A0*Cneg1 - 9*h*Bneg1*B0 + 4*h^3*Aneg1*A0,
    6*A1*Cneg1 - 6*A0*C0 + 9*h*B0^2 - 4*h^3*A0^2,
    6*Aneg1*C1 - 6*A0*C0 - 9*h*B0^2 + 4*h^3*A0^2,
    6*A1*Cneg2 - 6*A0*Cneg1 + 9*h*B0*Bneg1 - 28*h^3*A0*Aneg1 - 36*h^5*Bneg1,
    6*Aneg1*C2 - 6*A0*C1 - 9*h*B0*B1 + 28*h^3*A0*A1 + 36*h^5*B1,
    3*B1*C1 - 3*B0*C2 + 3*h*A1^2*A0 + 4*h^3*A1*B1,
    3*Bneg1*Cneg1 - 3*B0*Cneg2 - 3*h*Aneg1^2*A0 - 4*h^3*Aneg1*Bneg1,
    6*B1*C0 - 6*B0*C1 + 6*h*A1*A0^2 + 4*h^3*A0*B1 + h^3*A1*B0,
    6*Bneg1*C0 - 6*B0*Cneg1 - 6*h*Aneg1*A0^2 - 4*h^3*A0*Bneg1 - h^3*Aneg1*B0,
    6*B1*Cneg1 - 6*B0*C0 + 6*h*A0^3 + 5*h^3*A0*B0,
    6*Bneg1*C1 - 6*B0*C0 - 6*h*A0^3 - 5*h^3*A0*B0,
    6*B1*Cneg2 - 6*B0*Cneg1 + 6*h*A0^2*Aneg1 + 35*h^3*Aneg1*B0 - 84*h^4*Cneg1 + 4*h^7*Aneg1,
    6*Bneg1*C2 - 6*B0*C1 - 6*h*A0^2*A1 - 35*h^3*A1*B0 - 84*h^4*C1 - 4*h^7*A1,
    36*C2*C0 - 36*C1^2 + 54*h^2*A1*A0*B1 - 18*h^3*C2*A0 + 63*h^4*B1^2 + h^6*A1^2,
    36*Cneg2*C0 - 36*Cneg1^2 + 54*h^2*Aneg1*A0*Bneg1 + 18*h^3*Cneg2*A0 + 63*h^4*Bneg1^2 + h^6*Aneg1^2,
    9*C2*Cneg1 - 9*C1*C0 + 27*h^2*A1*A0*B0 + 36*h^3*C1*A0 + 18*h^4*B1*B0 + 2*h^6*A1*A0,
    9*Cneg2*C1 - 9*Cneg1*C0 + 27*h^2*Aneg1*A0*B0 - 36*h^3*Cneg1*A0 + 18*h^4*Bneg1*B0 + 2*h^6*Aneg1*A0,
    2*C2*Cneg2 - 2*C1*Cneg1 + 9*h^2*A1*Aneg1*B0 + 48*h^4*B0^2 + 32*h^6*A1*Aneg1 + 132*h^8*B0 - 8*h^12,
    18*C1*Cneg1 - 18*C0^2 + 27*h^2*A1*Aneg1*B0 + 126*h^4*B0^2 + 8*h^6*A0^2,
    6*C2*C1 - 3*B1^3 + 2*A1^3*A0 + 3*h^2*A1^2*B1,
    6*Cneg2*Cneg1 - 3*Bneg1^3 + 2*Aneg1^3*A0 + 3*h^2*Aneg1^2*Bneg1,
    6*C1^2 - 3*B1^2*B0 + 2*A1^3*Aneg1 + 12*h^2*A1*A0*B1 - 28*h^3*A1*C1,
    6*Cneg1^2 - 3*Bneg1^2*B0 + 2*Aneg1^3*A1 + 12*h^2*Aneg1*A0*Bneg1 + 28*h^3*Aneg1*Cneg1,
    6*C1*C0 - 3*B1*B0^2 + 2*A1*A0^3 + 3*h^2*A1*A0*B0 + 4*h^3*A0*C1,
    6*Cneg1*C0 - 3*Bneg1*B0^2 + 2*Aneg1*A0^3 + 3*h^2*Aneg1*A0*B0 - 4*h^3*A0*Cneg1,
    18*C0^2 - 9*B1*B0*Bneg1 + 6*A0^4 + 9*h^2*A0^2*B0 - 8*h^6*A0^2
];

# Pass to R to check which of the generators of the preimage that contains ker(pi_1) really lie in the kernel
image_gen_list = [pi_1(gen) for gen in gens(bihom_rho_bar_preimage)];
h_ideal = ideal(R, [h]);
print([ideal_membership(f, h_ideal) for f in image_gen_list]);  # returns true for all generators
coeffs_image_gen_list = [coordinates(p, h_ideal) for p in image_gen_list];

# We subract the h-multiples from the generators of the preimage to obtain a new ideal that contains ker(pi_1) and is contained in the bihomogeneous preimage of ker(pi_2) under rho_bar
kernel_superset_ideal = ideal(R,  [image_gen_list[i] - h*coeffs_image_gen_list[i][1] for i in 1:length(image_gen_list)]);

# By omitting the generator h, we obtain a homogeneous ideal I such that ker(pi_1) lies in I + <h>

test_5 = ideal(S, gens(bihom_rho_bar_preimage)[2:36]);
print(test_4 == test_5);  # confirms that we have obtained the same relations ideal as the one given by the relations of Berry

# Show that the for the other generators of the preimage that if we have that the sum of them and a suitable multiple of h lies in the kernel of pi_1, then this multiple of h has no preimage under pi_1, so we only need the the generators 2:36 of the preimage to get the relations ideal
coeff_test_1 = h*coeffs_image_gen_list[37][1];
(bool_coeff_test_1, test_preimage_1) = has_preimage_with_preimage(pi_1, coeff_test_1);  # Did not run through yet
print("There is a preimage for the first coefficient: ", bool_coeff_test_1);

coeff_test_2 = h*coeffs_image_gen_list[38][1];
(bool_coeff_test_2, test_preimage_2) = has_preimage_with_preimage(pi_1, coeff_test_2);  # Did not run through yet
print("There is a preimage for the second coefficient: ", bool_coeff_test_2);

coeff_test_3 = h*coeffs_image_gen_list[39][1];
(bool_coeff_test_3, test_preimage_3) = has_preimage_with_preimage(pi_1, coeff_test_3);  # Did not run through yet
print("There is a preimage for the third coefficient: ", bool_coeff_test_3);

coeff_test_4 = h*coeffs_image_gen_list[40][1];
(bool_coeff_test_4, test_preimage_4) = has_preimage_with_preimage(pi_1, coeff_test_4);  # Did not run through yet
print("There is a preimage for the fourth coefficient: ", bool_coeff_test_4);

coeff_test_5 = h*coeffs_image_gen_list[41][1];
(bool_coeff_test_5, test_preimage_5) = has_preimage_with_preimage(pi_1, coeff_test_5);  # Did not run through yet
print("There is a preimage for the fifth coefficient: ", bool_coeff_test_5);

coeff_test_6 = h*coeffs_image_gen_list[42][1];
(bool_coeff_test_6, test_preimage_6) = has_preimage_with_preimage(pi_1, coeff_test_6);  # Did not run through yet
print("There is a preimage for the sixth coefficient: ", bool_coeff_test_6);