// Initialize the number field and the polynomial ring
Q<t> := PolynomialRing(RationalField());
K<zeta> := NumberField(t^4 - t^2 + 1);
i := zeta^3;      // imaginary unit
sigma := zeta^4;  // primitive third root of unity

// Take the invariants of G_5_symp that were compututed in G_5_reflections_blowups.jl using Oscar
A<x1, x2, x3, x4> := PolynomialRing(K, 4, "grevlex");

invar_1 := x1*x3 + x2*x4;
invar_2 := x1^5*x2 - x1*x2^5;
invar_3 := x1*x2^2*x3^3 - x2^3*x3^2*x4 - x1^3*x3*x4^2 + x1^2*x2*x4^3;
invar_4 := x3^5*x4 - x3*x4^5;
invar_5 := x1^4*x2^3*x3 + (1/7)*x2^7*x3 - (1/7)*x1^7*x4 - x1^3*x2^4*x4;
invar_6 := x2^4*x3^4 - 4*x1^3*x2*x3^3*x4 + 6*x1^2*x2^2*x3^2*x4^2
           - 4*x1*x2^3*x3*x4^3 + x1^4*x4^4;
invar_7 := x2*x3^7 - 7*x1*x3^4*x4^3 + 7*x2*x3^3*x4^4 - x1*x4^7;
invar_8 := x1^12 - 33*x1^8*x2^4 - 33*x1^4*x2^8 + x2^12;
invar_9 := x1^4*x2^5*x3^3 - (1/9)*x2^9*x3^3 - x1^7*x2^2*x3^2*x4
           - (5/3)*x1^3*x2^6*x3^2*x4 + (5/3)*x1^6*x2^3*x3*x4^2
           + x1^2*x2^7*x3*x4^2 + (1/9)*x1^9*x4^3 - x1^5*x2^4*x4^3;
invar_10 := x1^4*x2^2*x3^6 - (1/2)*x2^6*x3^6 - 3*x1^3*x2^3*x3^5*x4
            + (15/2)*x1^2*x2^4*x3^4*x4^2 - 5*x1^5*x2*x3^3*x4^3
            - 5*x1*x2^5*x3^3*x4^3 + (15/2)*x1^4*x2^2*x3^2*x4^4
            - 3*x1^3*x2^3*x3*x4^5 - (1/2)*x1^6*x4^6 + x1^2*x2^4*x4^6;
invar_11 := x2^3*x3^9 - 9*x1^2*x2*x3^7*x4^2 + 15*x1*x2^2*x3^6*x4^3
            - 9*x2^3*x3^5*x4^4 + 9*x1^3*x3^4*x4^5
            - 15*x1^2*x2*x3^3*x4^6 + 9*x1*x2^2*x3^2*x4^7 - x1^3*x4^9;
invar_12 := x3^12 - 33*x3^8*x4^4 - 33*x3^4*x4^8 + x4^12;

invars := [invar_1, invar_2, invar_3, invar_4, invar_5, invar_6, 
    invar_7, invar_8, invar_9, invar_10, invar_11, invar_12
];

// The invariant ring is the algebra generated by the invars and therefore it is isomorphic to the quotient of the polynomial ring in 12 variables by the relation ideal
B<[y]> := PolynomialRing(K, 12, "grevlex");
U := RelationIdeal(invars, B);  // Exceeds the memory limit of the student version of Magma
