using Oscar
Qx, s = QQ["s"];

K, i = number_field(s^2 + 1, "i");

Kt, t = K["t"];

L, zeta3 = number_field(t^2 + t + 1, "zeta3");

# S_0 representation of the binary tetrahedral group
tau = matrix(L, 2, 2, [(-1-i)/2 (1-i)/2; (-1-i)/2 (-1 + i)/2]);
I_m = matrix(L, 2, 2, [i 0; 0 -i]);
G = matrix_group([tau, I_m]);
#print(order(G))

# S_1 representation of the binary tetrahedral group
tau_1 = zeta3 * tau;
G_4 = matrix_group([tau_1, I_m]);
describe(G_4);
conj = conjugacy_classes(G_4);  # Somehow this only wortks after executing describe(G_4) once

# generators of G_4 according to Lehrer-Taylor
r_1 = tau_1;
r = matrix(L, 2, 2, [1 0; 0 -1]);
r_1prime = r*r_1*r;
G_4_LT = matrix_group([r_1, r_1prime]);
describe(G_4_LT);
print(G_4 == G_4_LT)  # confirm that the two groups are equal, hence G_4 is equivalently generated by the reflections r_1 and r_1prime

# representatives of the two conjugacy classes of elements of order 3
rep_1 = representative(conj[4]);  # representative of the first conjugacy class of elements of order 3, including tau_1
rep_2 = representative(conj[6]);  # representative of the second conjugacy class of elements of order 3
class_1 = collect(conj[4]);  # list of elements in the first conjugacy class, class_1[2] == tau_1
class_2 = collect(conj[6]);  # list of elements in the second conjugacy class, it holds inv(class_1[k]) == class_2[k]
class_1_symp = [transpose(inv(matrix(g))) for g in class_1];
class_2_symp = [transpose(inv(matrix(g))) for g in class_2];

# Define eigenvectors of the 4 elements of order 3 corresponding to the eigenvalue 1
V = vector_space(L, 2);

# Note that the group operation in Oscar on vectors v of a matrix group G is defined as v*g, hence we need to take the transpose of the matrices to verify the eigenvector property
G_4_transpose = matrix_group([transpose(tau_1), transpose(I_m)]);
v_1 = V([L((i - 1)*zeta3 - 1), L(1)]);  # for class_1[1]
S_1 = stabilizer(G_4_transpose, v_1);  # order(S_1[1]) yields 3, hence a nontrivial isotropy group
v_2 = V([L((-i + 1)*zeta3 + 1), L(1)]);  # for class_1[2]
S_2 = stabilizer(G_4_transpose, v_2);  # order(S_2[1]) yields 3, hence a nontrivial isotropy group
v_3 = V([L((-i - 1)*zeta3 - 1), L(1)]);  # for class_1[3]
S_3 = stabilizer(G_4_transpose, v_3);  # order(S_3[1]) yields 3, hence a nontrivial isotropy group
v_4 = V([L((i + 1)*zeta3 + 1), L(1)]);  # for class_1[4]
S_4 = stabilizer(G_4_transpose, v_4);  # order(S_4[1]) yields 3, hence a nontrivial isotropy group

# Define vanishing locus of the union of the 4 lines given by the eigenvectors
R, y = polynomial_ring(L, ["y[1]", "y[2]", "y[3]", "y[4]"]);
p_1 = y[1] - ((i - 1)*zeta3 - 1)*y[2];
p_2 = y[1] - ((-i + 1)*zeta3 + 1)*y[2];
p_3 = y[1] - ((-i - 1)*zeta3 - 1)*y[2];
p_4 = y[1] - ((i + 1)*zeta3 + 1)*y[2];
c_1 = p_1*p_2*p_3*p_4;  # y[1]^4 - (4*zeta3 + 2)*y[1]^2*y[2]^2 + y[2]^4

# Test invariance of c_1 under the group action
# We want to verify that C_1 is invariant under the group action, i.e. for each g in G_4 we get that g*v_k is again contained in one of the lines spanned by v_1, v_2, v_3, v_4
# Function that checks which vectors from a given list are mapped to scalar multiples of vectors from the same list under the action of a list of matrices
function check_scalar_multiples(matrices, vectors)
    n = length(matrices)
    k = length(vectors)
    
    # Create a zero matrix of size (number of matrices) x (number of vectors)
    res_matrix = zeros(Int, n, k)
    
    # We assume that none of the vectors has a zero second component
    function get_ratio(v)
        return v[1] // v[2]
    end

    # Pre-calculate ratios for the input vectors
    target_ratios = [get_ratio(v) for v in vectors]
    
    for i in 1:n
        for j in 1:k
            m = matrices[i]
            v = vectors[j]
            
            # 1. Compute w = m * v
            w = m * v
            
            # 2. Compute the ratio w[1] / w[2]
            w_ratio = get_ratio(w)
            
            # 3. Compare to the target ratios
            for (idx, target) in enumerate(target_ratios)
                if w_ratio == target
                    # Overwrite the 0 with the index of the matching vector
                    res_matrix[i, j] = idx
                    break
                end
            end
        end
    end
    
    return res_matrix
end

v_1_matrix = matrix(L, 2, 1, [(i - 1)*zeta3 - 1; 1]);
v_2_matrix = matrix(L, 2, 1, [(-i + 1)*zeta3 + 1; 1]);
v_3_matrix = matrix(L, 2, 1, [(-i - 1)*zeta3 - 1; 1]);
v_4_matrix = matrix(L, 2, 1, [(i + 1)*zeta3 + 1; 1]);
G_4_list = collect(G_4);
vectors_list = [v_1_matrix, v_2_matrix, v_3_matrix, v_4_matrix];

result_G_4 = check_scalar_multiples(G_4_list, vectors_list);

# We want to find the set of reflecting hyperplanes of the group G_4, which are given by the vanishing locus of the linear forms corresponding to the eigenvectors
eigenvals = [eigenvalues(matrix(g)) for g in G_4_list];

# S_2 representation of the binary tetrahedral group
tau_2 = zeta3^2 * tau;
G_4_dual = matrix_group([tau_2, I_m]);
describe(G_4_dual);
conj_dual = conjugacy_classes(G_4_dual);  # Somehow this only wortks after executing describe(G_4_dual) once

# representatives of the two conjugacy classes of elements of order 3
rep_1_dual = representative(conj_dual[4]);  # representative of the first conjugacy class of elements of order 3
rep_2_dual = representative(conj_dual[6]);  # representative of the second conjugacy class of elements of order 3, including tau_2
class_1_dual = collect(conj_dual[4]);  # list of elements in the first conjugacy class, it holds inv(class_1_dual[k]) == class_2_dual[k]
class_2_dual = collect(conj_dual[6]);  # list of elements in the second conjugacy class, class_2_dual[3] == tau_2
class_1_dual_symp = [transpose(inv(matrix(g))) for g in class_1_dual];
class_2_dual_symp = [transpose(inv(matrix(g))) for g in class_2_dual];

# Define eigenvectors of the 4 elements of order 3 corresponding to the eigenvalue 1, as above we need the transpose to verify the eigenvector property
G_4_dual_transpose = matrix_group([transpose(tau_2), transpose(I_m)]);
v_1_dual = V([L((-i - 1)*zeta3 - i), L(1)]);  # for class_2_dual[1]
S_1_dual = stabilizer(G_4_dual_transpose, v_1_dual);  # order(S_1_dual[1]) yields 3, hence a nontrivial isotropy group
v_2_dual = V([L((i + 1)*zeta3 + i), L(1)]);  # for class_2_dual[2]
S_2_dual = stabilizer(G_4_dual_transpose, v_2_dual);  # order(S_2_dual[1]) yields 3, hence a nontrivial isotropy group
v_3_dual = V([L((i - 1)*zeta3 + i), L(1)]);  # for class_2_dual[3]
S_3_dual = stabilizer(G_4_dual_transpose, v_3_dual);  # order(S_3_dual[1]) yields 3, hence a nontrivial isotropy group
v_4_dual = V([L((-i + 1)*zeta3 - i), L(1)]);  # for class_2_dual[4]
S_4_dual = stabilizer(G_4_dual_transpose, v_4_dual);  # order(S_4_dual[1]) yields 3, hence a nontrivial isotropy group

# Define vanishing locus of the union of the 4 lines given by the eigenvectors
p_1_dual = y[3] - ((-i - 1)*zeta3 - i)*y[4];
p_2_dual = y[3] - ((i + 1)*zeta3 + i)*y[4];
p_3_dual = y[3] - ((i - 1)*zeta3 + i)*y[4];
p_4_dual = y[3] - ((-i + 1)*zeta3 - i)*y[4];
c_2 = p_1_dual*p_2_dual*p_3_dual*p_4_dual;  # y[3]^4 + (4*zeta3 + 2)*y[3]^2*y[4]^2 + y[4]^4

# Test invariance of c_2 under the group action, as above we want to verify that C_2 is invariant under the group action
v_1_dual_matrix = matrix(L, 2, 1, [(-i - 1)*zeta3 - i; 1]);
v_2_dual_matrix = matrix(L, 2, 1, [(i + 1)*zeta3 + i; 1]);
v_3_dual_matrix = matrix(L, 2, 1, [(i - 1)*zeta3 + i; 1]);
v_4_dual_matrix = matrix(L, 2, 1, [(-i + 1)*zeta3 - i; 1]);
G_4_dual_list = collect(G_4_dual);
vectors_dual_list = [v_1_dual_matrix, v_2_dual_matrix, v_3_dual_matrix, v_4_dual_matrix];
result_G_4_dual = check_scalar_multiples(G_4_dual_list, vectors_dual_list);

# symplectifications
tau_symp = block_diagonal_matrix([tau_1, transpose(inv(tau_1))]);
I_symp = block_diagonal_matrix([I_m, transpose(inv(I_m))]);
G_symp = matrix_group([tau_symp, I_symp]);
IR = invariant_ring(G_symp);
poly_invar = polynomial_ring(IR);
u = gens(poly_invar);
invars = fundamental_invariants(IR);
invars_ideal_1 = ideal(poly_invar, invars);  # Except the third invariant in this list, they coincide with the ones in the paper of Lehn and Sorger

# Multiply the third invariant with (-2*zeta3 - 1) to obtain the invariant given in the paper of Lehn and Sorger
invars[3] = (-2*zeta3 - 1) * invars[3];
invars_ideal_2 = ideal(poly_invar, invars);
print(invars_ideal_1 == invars_ideal_2)  # confirm that both ideals are equal

tau_symp_transpose = transpose(inv(tau_symp));
I_symp_transpose = transpose(inv(I_symp));
G_symp_transpose = matrix_group([inv(tau_symp_transpose), inv(I_symp_transpose)]);
IR_transpose = invariant_ring(G_symp_transpose);
poly_invar_transpose = polynomial_ring(IR_transpose);
u_t = gens(poly_invar_transpose);
invars_transpose = fundamental_invariants(IR_transpose);
invars_ideal_transpose_1 = ideal(poly_invar_transpose, invars_transpose);
gens(invars_ideal_1)
gens(invars_ideal_transpose_1)  # We cannot use the '==' operator here, since the invariants are defined over differnt polynomial rings
# There is a sign difference in the some invariants compared to the previous ones, hence we know that the right action is used by Lehn and Sorger

# Redefine the invariants in order to compare them directly in the same ring
T, w = polynomial_ring(L, ["w[1]", "w[2]", "w[3]", "w[4]"]);
I_test_1 = ideal(T, [
    w[1]*w[3] + w[2]*w[4],
    w[1]^4 + (4*zeta3 + 2)*w[1]^2*w[2]^2 + w[2]^4,
    w[1]^2*w[2]*w[3] + (2//3*zeta3 + 1//3)*w[2]^3*w[3] + (-2//3*zeta3 - 1//3)*w[1]^3*w[4] - w[1]*w[2]^2*w[4],
    w[2]*w[3]^3 + (-2*zeta3 - 1)*w[1]*w[3]^2*w[4] + (2*zeta3 + 1)*w[2]*w[3]*w[4]^2 - w[1]*w[4]^3,
    w[3]^4 + (-4*zeta3 - 2)*w[3]^2*w[4]^2 + w[4]^4,
    w[1]^5*w[2] - w[1]*w[2]^5,
    w[1]*w[2]^2*w[3]^3 - w[2]^3*w[3]^2*w[4] - w[1]^3*w[3]*w[4]^2 + w[1]^2*w[2]*w[4]^3,
    w[3]^5*w[4] - w[3]*w[4]^5])
I_test_2 = ideal(T, [
    w[1]*w[3] + w[2]*w[4],
    w[1]^4 + (-4*zeta3 - 2)*w[1]^2*w[2]^2 + w[2]^4,
    w[1]^2*w[2]*w[3] + (-2//3*zeta3 - 1//3)*w[2]^3*w[3] + (2//3*zeta3 + 1//3)*w[1]^3*w[4] - w[1]*w[2]^2*w[4],
    w[2]*w[3]^3 + (2*zeta3 + 1)*w[1]*w[3]^2*w[4] + (-2*zeta3 - 1)*w[2]*w[3]*w[4]^2 - w[1]*w[4]^3,
    w[3]^4 + (4*zeta3 + 2)*w[3]^2*w[4]^2 + w[4]^4,
    w[1]^5*w[2] - w[1]*w[2]^5,
    w[1]*w[2]^2*w[3]^3 - w[2]^3*w[3]^2*w[4] - w[1]^3*w[3]*w[4]^2 + w[1]^2*w[2]*w[4]^3,
    w[3]^5*w[4] - w[3]*w[4]^5])
print(I_test_1 == I_test_2)  # This confirms that the invariants for the left and right action differ


# symplectifications for the dual (S_2) representation
tau_dual_symp = block_diagonal_matrix([tau_2, transpose(inv(tau_2))]);
I_dual_symp = block_diagonal_matrix([I_m, transpose(inv(I_m))]);
G_dual_symp = matrix_group([tau_dual_symp, I_dual_symp]);
IR_dual = invariant_ring(G_dual_symp);
poly_invar_dual = polynomial_ring(IR_dual);
u_dual = gens(poly_invar_dual);
invars_dual = fundamental_invariants(IR_dual);
invars_dual_ideal_1 = ideal(poly_invar_dual, invars_dual);

invars_dual[3] = (2*zeta3 + 1) * invars_dual[3];
invars_dual_ideal_2 = ideal(poly_invar_dual, invars_dual);
print(invars_dual_ideal_1 == invars_dual_ideal_2)  # confirm that both ideals are equal


# We want to identify the normal subgroup Q_8 in the symplectified group G_symp
G_symp_list = collect(G_symp);
normal_G_symp = normal_subgroups(G_symp);
print(describe(normal_G_symp[2]));  # The second normal subgroup is isomorphic to Q_8
Q8_symp = normal_G_symp[2];
Q8_symp_list = collect(Q8_symp);

C_3, pi = quo(G_symp, Q8_symp);
id = collect(C_3)[1];
f1 = collect(C_3)[2];
f2 = collect(C_3)[3];

v_1 = matrix(L, 4, 1, [(i - 1)*zeta3 - 1; 1; 0; 0]);
v_2 = matrix(L, 4, 1, [(-i + 1)*zeta3 + 1; 1; 0; 0]);
v_3 = matrix(L, 4, 1, [(-i - 1)*zeta3 - 1; 1; 0; 0]);
v_4 = matrix(L, 4, 1, [(i + 1)*zeta3 + 1; 1; 0; 0]);

# Compute preimages of the cosets under the natural projection pi: G_symp -> C_3 to obtain representatives of the cosets of Q_8 in G_symp
pre_id = preimage(pi, id);
pre_f1 = preimage(pi, f1);
pre_f2 = preimage(pi, f2);

# Compute the quotient variety by Q_8
Q8_invars = invariant_ring(Q8_symp);
poly_Q8 = polynomial_ring(Q8_invars);
u_Q8 = gens(poly_Q8);
Q8_invars_list = fundamental_invariants(Q8_invars);

A_Q8, x = polynomial_ring(L, :x => (1:4));
inv_1 = x[1]*x[3] + x[2]*x[4];
inv_2 = x[3]^4 + x[4]^4;
inv_3 = x[2]*x[3]^3 - x[1]*x[4]^3;
inv_4 = x[3]^2*x[4]^2;
inv_5 = x[1]*x[3]^2*x[4] - x[2]*x[3]*x[4]^2;
inv_6 = x[1]^2*x[3]^2 + x[2]^2*x[4]^2;
inv_7 = x[2]^2*x[3]^2 + x[1]^2*x[4]^2;
inv_8 = x[1]^2*x[2]*x[3] - x[1]*x[2]^2*x[4];
inv_9 = x[2]^3*x[3] - x[1]^3*x[4];
inv_10 = x[1]^4 + x[2]^4;
inv_11 = x[1]^2*x[2]^2;
inv_12 = x[3]^5*x[4] - x[3]*x[4]^5;
inv_13 = x[1]*x[3]^5 + x[2]*x[4]^5;
inv_14 = x[1]*x[2]*x[3]^4 - x[1]*x[2]*x[4]^4;
inv_15 = x[1]*x[2]^2*x[3]^3 + x[1]^2*x[2]*x[4]^3;
inv_16 = x[1]*x[2]^3*x[3]^2 - x[1]^3*x[2]*x[4]^2;
inv_17 = x[1]^5*x[3] + x[2]^5*x[4];
inv_18 = x[1]^5*x[2] - x[1]*x[2]^5;

R_Q8, z = polynomial_ring(L, :z => (1:18));
f = hom(R_Q8, A_Q8, [inv_1, inv_2, inv_3, inv_4, inv_5, inv_6, inv_7, inv_8, inv_9, inv_10, inv_11, inv_12, inv_13, inv_14, inv_15, inv_16, inv_17, inv_18]);
relations_ideal = kernel(f);
basis_relations = standard_basis(relations_ideal, ordering=negdegrevlex(R_Q8));
basis_relations_ideal = ideal(R_Q8, collect(basis_relations));

S_Q8, pr = quo(R_Q8, basis_relations_ideal);

# Check if the lines given by the eigenvectors coincide in the quotient variety by Q_8
line_1 = x[1] - ((i - 1)*zeta3 - 1)*x[2];
line_1_lifted = preimage(f, ideal(A_Q8, [line_1, x[3], x[4]]));
line_2 = x[1] - ((-i + 1)*zeta3 + 1)*x[2];
line_2_lifted = preimage(f, ideal(A_Q8, [line_2, x[3], x[4]]));
line_3 = x[1] - ((-i - 1)*zeta3 - 1)*x[2];
line_3_lifted = preimage(f, ideal(A_Q8, [line_3, x[3], x[4]]));
line_4 = x[1] - ((i + 1)*zeta3 + 1)*x[2];
line_4_lifted = preimage(f, ideal(A_Q8, [line_4, x[3], x[4]]));
print(pr(line_1_lifted) == pr(line_2_lifted))  # true
print(pr(line_1_lifted) == pr(line_3_lifted))  # true
print(pr(line_1_lifted) == pr(line_4_lifted))  # true

line_1_dual = x[3] - ((-i - 1)*zeta3 - i)*x[4];
line_1_dual_lifted = preimage(f, ideal(A_Q8, [line_1_dual, x[1], x[2]]));
line_2_dual = x[3] - ((i + 1)*zeta3 + i)*x[4];
line_2_dual_lifted = preimage(f, ideal(A_Q8, [line_2_dual, x[1], x[2]]));
line_3_dual = x[3] - ((i - 1)*zeta3 + i)*x[4];
line_3_dual_lifted = preimage(f, ideal(A_Q8, [line_3_dual, x[1], x[2]]));
line_4_dual = x[3] - ((-i + 1)*zeta3 - i)*x[4];
line_4_dual_lifted = preimage(f, ideal(A_Q8, [line_4_dual, x[1], x[2]]));
print(pr(line_1_dual_lifted) == pr(line_2_dual_lifted))  # true
print(pr(line_1_dual_lifted) == pr(line_3_dual_lifted))  # true
print(pr(line_1_dual_lifted) == pr(line_4_dual_lifted))  # true

line_1_new = -i*x[1] - ((-i - 1)*zeta3 - i)*x[2];  # obtainend by G_symp_list[15]*v_1
line_1_new_lifted = preimage(f, ideal(A_Q8, [line_1_new, x[3], x[4]]));
print(pr(line_1_lifted) == pr(line_1_new_lifted))  # true
line_2_new = ((i + 1)*zeta3 + i)*x[1] - i*x[2];  # obtainend by G_symp_list[15]*v_2
line_2_new_lifted = preimage(f, ideal(A_Q8, [line_2_new, x[3], x[4]]));
print(pr(line_2_lifted) == pr(line_2_new_lifted))  # true
line_3_new = ((i + 1)*zeta3 + 1)*x[1] - x[2];  # obtainend by G_symp_list[15]*v_3
line_3_new_lifted = preimage(f, ideal(A_Q8, [line_3_new, x[3], x[4]]));
print(pr(line_3_lifted) == pr(line_3_new_lifted))  # true
line_4_new = x[1] + ((-i - 1)*zeta3 - 1)*x[2];  # obtainend by G_symp_list[15]*v_4
line_4_new_lifted = preimage(f, ideal(A_Q8, [line_4_new, x[3], x[4]]));
print(pr(line_4_lifted) == pr(line_4_new_lifted))  # true